sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8
branches:
  only:
  - develop
  - master
notifications:
  email:
    recipients:
    - cedar-core-developers@lists.stanford.edu
    on_success: never
    on_failure: always
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=false clean deploy --settings .m2/travis-settings.xml'
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=true clean --settings .m2/travis-settings.xml'
env:
  global:
  - secure: FFydfmribYTKP26n/sGFa2X2p+pqu+eKcCbEsKuTD7DjTIKroOyKbM8wRhmMMpefrP1DZiYlPscE1yjmPLd4c7roPLwRG124a3B4MvmSqVaxe6yAXpOM+y5gHg00UXvVtouOOaqkVh32AYSyQVoBK3+ZxHED7YLMZTlQQ7lzhwp21zisni1FXDC4N5u/a8tk8X3JSophzZuqhOU63bBl18M+C7fCWNA0AK+Xex74E7j06+YcvOWcaDId48k/0lwBRzr+fLDH0jp+flsotgB3LYFpgLRK6uVc2Ixfp79ukCSoFgGNv4Ai+V69sOa1Wx9m1i0kItKq9lAeb/mZiTc9VRygD/p7ChUjod8wzw6C/dt1DaCDWvz9UnL8kvhV2jUB/VD+ik83dT+V0AiMQPZHpB3ecsGT5+rR40lwqfwX4+6xYbtsyRMEZJdTfneK2wix/7DfzYB13BWtFRrDqhM1+fWD1Z+xNJEqpEMmYJSUMgbJ9xXSeEmTdTCm4pDyGUkRMrB9FUiF8Z9i4R0MBWTTQKXpdBthF7PDY0fyycldlcBvYVZoHy1FCzG5QEeAmy1W4+7Wp5YYgfR3ULNIhPibtm8mCIFpR4xWD73jAdnIUc4/y2p1iuhP4vOL5jYxhakuuwWbYmeUWrcIu1wrzbu+LtEAa6dR67J7WUkJLhLu6r8=
  - secure: 5dIhgEitNLVS8FgAEfLr8UuZpWfgCvvL/uQi3/fsMmG8Ut6TgQGNeNEeRVvz4RCoKht27f0QX+R+jiLztbPzyoSr1/IdDeAS9ZKG8VmSJ8z78ygN/ejxLpp85MLxlMtCCSZuMqlrB93y3bH/dTs9vHylf6UOpDm1IyA6E6Ctz006h3r/9obrRPjD6/8v9iSZOMSAh+PzzpMf2hB3j6y9/Nr9EsKTVdAF1aRsOHqCXQpnyHQyhGg8nLTi0f09nJYwc1ZZ/oqaHCiRTOGnOTo7F4/LB5h9mwYiFqbsbhULICC+dxaL/7YSbvTDWvcQQpEaff2eQi5M+aaR1InEzG/PtOkGVIG5lsao+iPl3DbvrfKIuCSLCx7WCGMQSdOSy28qQ7Y4QQ9WlT4e8pbqfvh5CzJhXHOgAKhU86YI/6NbqdDExlN8Tp2YVC7M/zhrj8SjEaLC1Xi8xDWj09lEeD00jcdvAaPF/BZ0EQ+KxRAZprXLOLDKhqZEovJQw0N67AyQxCZGIIq+N3qiV2z39ptzkdjQ63j8gZPayMmiCN2PhNydEeF+XGzYx2jfUxoRBh7w1wOhfx5sf4HQnEi6rgqKLjKR3F+x38sfvIJ2lb4U0KacrGjlPwOc0Ti/OrdlKKBsuy2SJV2bBcRwS/u72yvjkVnd2uTSldc+oZGiO2kzHm0=
